/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Interfaz_Proveedores extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Interfaz_Proveedores() {
        initComponents();
        String columnas[]={"RUC","Nombre","Dirección","Telefono","Provincia","Ciudad"};
        this.tabla.setColumnIdentifiers(columnas);
        this.Tabla_Proveedor.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Agregar_Pro = new javax.swing.JButton();
        Btn_Modificar_Pro = new javax.swing.JButton();
        Btn_Eliminar_Pro = new javax.swing.JButton();
        ComboBox_QueBusca = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Proveedor = new javax.swing.JTable();
        Texto_Buscar_Pro = new javax.swing.JTextField();
        Btn_Buscar_Pro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(730, 250));
        setPreferredSize(new java.awt.Dimension(930, 490));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Agregar_Pro.setText("Agregar");
        Btn_Agregar_Pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Agregar_ProActionPerformed(evt);
            }
        });
        add(Btn_Agregar_Pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 130, 40));

        Btn_Modificar_Pro.setText("Modificar");
        add(Btn_Modificar_Pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 130, 40));

        Btn_Eliminar_Pro.setText("Eliminar");
        add(Btn_Eliminar_Pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 130, 40));

        ComboBox_QueBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "RUC" }));
        add(ComboBox_QueBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 110, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        Tabla_Proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cedula1", "Nombre", "Direccion", "Provincia", "Ciudad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla_Proveedor.setGridColor(new java.awt.Color(102, 102, 102));
        Tabla_Proveedor.setRowHeight(30);
        Tabla_Proveedor.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Tabla_Proveedor);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 870, 350));

        Texto_Buscar_Pro.setText("Buscar");
        add(Texto_Buscar_Pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 150, -1));

        Btn_Buscar_Pro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BTN_Buscar.png"))); // NOI18N
        add(Btn_Buscar_Pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 35, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo_Paginas.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Agregar_ProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Agregar_ProActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Btn_Agregar_ProActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        agrInt.dispose();
    }//GEN-LAST:event_formMouseClicked

    public Interfaz_Agregar_Proveedor agrInt=new Interfaz_Agregar_Proveedor();
    public DefaultTableModel tabla = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hacer todas las celdas no editables
            }
        };
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn_Agregar_Pro;
    public javax.swing.JLabel Btn_Buscar_Pro;
    public javax.swing.JButton Btn_Eliminar_Pro;
    public javax.swing.JButton Btn_Modificar_Pro;
    public javax.swing.JComboBox<String> ComboBox_QueBusca;
    public javax.swing.JTable Tabla_Proveedor;
    public javax.swing.JTextField Texto_Buscar_Pro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
