/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Interfaz_Venta extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Interfaz_Venta() {
        initComponents();
        String columnas[] = {"Fecha", "Codigo", "Codigo Cliente"};
        this.tabla.setColumnIdentifiers(columnas);
        this.Tabla_Facturas.setModel(tabla);
        String columnasProd[] = {"Codigo Producto", "Precio unitario","Cantidad","Total"};
        this.tablaProd.setColumnIdentifiers(columnasProd);
        this.Tabla_Productos_F.setModel(tablaProd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Agregar_Comp = new javax.swing.JButton();
        Btn_Eliminar_Comp = new javax.swing.JButton();
        ComboBox_QueBusca = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_Productos_F = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Facturas = new javax.swing.JTable();
        Texto_Buscar_Comp = new javax.swing.JTextField();
        Btn_Buscar_Comp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(730, 250));
        setPreferredSize(new java.awt.Dimension(930, 490));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Agregar_Comp.setText("Agregar");
        Btn_Agregar_Comp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Agregar_CompActionPerformed(evt);
            }
        });
        add(Btn_Agregar_Comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 130, 40));

        Btn_Eliminar_Comp.setText("Eliminar");
        add(Btn_Eliminar_Comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 130, 40));

        ComboBox_QueBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Cedula" }));
        add(ComboBox_QueBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 110, -1));

        Tabla_Productos_F.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo Producto", "Precio Unitario", "Cantidad", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabla_Productos_F);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 60, 490, 350));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        Tabla_Facturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Código producto", "Código Proveedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla_Facturas.setGridColor(new java.awt.Color(102, 102, 102));
        Tabla_Facturas.setRowHeight(15);
        Tabla_Facturas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Tabla_Facturas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 370, 350));

        Texto_Buscar_Comp.setText("Buscar");
        add(Texto_Buscar_Comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 150, -1));

        Btn_Buscar_Comp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BTN_Buscar.png"))); // NOI18N
        add(Btn_Buscar_Comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 35, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo_Paginas.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Agregar_CompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Agregar_CompActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Btn_Agregar_CompActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        agrInt.dispose();
    }//GEN-LAST:event_formMouseClicked

    public Interfaz_AgregarFactura agrInt = new Interfaz_AgregarFactura();
    public DefaultTableModel tabla = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Hacer todas las celdas no editables
        }
    };
    public DefaultTableModel tablaProd = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Hacer todas las celdas no editables
        }
    };
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn_Agregar_Comp;
    public javax.swing.JLabel Btn_Buscar_Comp;
    public javax.swing.JButton Btn_Eliminar_Comp;
    public javax.swing.JComboBox<String> ComboBox_QueBusca;
    public javax.swing.JTable Tabla_Facturas;
    public javax.swing.JTable Tabla_Productos_F;
    public javax.swing.JTextField Texto_Buscar_Comp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
