/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Interfaz_Usuarios extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Interfaz_Usuarios() {
        initComponents();
        String columnas[]={"Usuario"};
        this.tabla.setColumnIdentifiers(columnas);
        this.Tabla_Usuarios.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Agregar_U = new javax.swing.JButton();
        Btn_Modificar_U = new javax.swing.JButton();
        Btn_Eliminar_U = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Usuarios = new javax.swing.JTable();
        Texto_Buscar_U = new javax.swing.JTextField();
        Btn_Buscar = new javax.swing.JLabel();
        Txt_Clave = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        BTN_Ver = new javax.swing.JButton();
        Ch_Provincias = new javax.swing.JCheckBox();
        Ch_Usuarios = new javax.swing.JCheckBox();
        Ch_Kardex = new javax.swing.JCheckBox();
        Ch_Compra = new javax.swing.JCheckBox();
        Ch_Venta = new javax.swing.JCheckBox();
        Ch_Proveedores = new javax.swing.JCheckBox();
        Ch_Clientes = new javax.swing.JCheckBox();
        Ch_Productos = new javax.swing.JCheckBox();
        Lbl_Img_Usuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(730, 250));
        setPreferredSize(new java.awt.Dimension(930, 490));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Agregar_U.setText("Agregar");
        Btn_Agregar_U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Agregar_UActionPerformed(evt);
            }
        });
        add(Btn_Agregar_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 130, 40));

        Btn_Modificar_U.setText("Modificar");
        add(Btn_Modificar_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 130, 40));

        Btn_Eliminar_U.setText("Eliminar");
        add(Btn_Eliminar_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 130, 40));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        Tabla_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla_Usuarios.setGridColor(new java.awt.Color(102, 102, 102));
        Tabla_Usuarios.setRowHeight(30);
        Tabla_Usuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Tabla_Usuarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 370, 350));

        Texto_Buscar_U.setText("Buscar");
        add(Texto_Buscar_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 260, -1));

        Btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BTN_Buscar.png"))); // NOI18N
        add(Btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 35, 35));

        Txt_Clave.setEditable(false);
        add(Txt_Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 150, 40));

        jLabel2.setText("Contraseña");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 110, 30));

        BTN_Ver.setText("Ver");
        BTN_Ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BTN_VerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BTN_VerMouseReleased(evt);
            }
        });
        add(BTN_Ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 60, -1));

        Ch_Provincias.setText("Provincias");
        Ch_Provincias.setEnabled(false);
        Ch_Provincias.setFocusable(false);
        add(Ch_Provincias, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 110, 40));

        Ch_Usuarios.setText("Usuarios");
        Ch_Usuarios.setEnabled(false);
        Ch_Usuarios.setFocusable(false);
        add(Ch_Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 110, 40));

        Ch_Kardex.setText("Kardex");
        Ch_Kardex.setEnabled(false);
        Ch_Kardex.setFocusable(false);
        add(Ch_Kardex, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 110, 40));

        Ch_Compra.setText("Compra");
        Ch_Compra.setEnabled(false);
        Ch_Compra.setFocusable(false);
        add(Ch_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 110, 40));

        Ch_Venta.setText("Venta");
        Ch_Venta.setToolTipText("");
        Ch_Venta.setEnabled(false);
        Ch_Venta.setFocusable(false);
        add(Ch_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 110, 40));

        Ch_Proveedores.setText("Proveedores");
        Ch_Proveedores.setEnabled(false);
        Ch_Proveedores.setFocusable(false);
        add(Ch_Proveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 110, 40));

        Ch_Clientes.setText("Clientes");
        Ch_Clientes.setEnabled(false);
        Ch_Clientes.setFocusable(false);
        add(Ch_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 110, 40));

        Ch_Productos.setText("Productos");
        Ch_Productos.setEnabled(false);
        Ch_Productos.setFocusable(false);
        add(Ch_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 110, 40));
        add(Lbl_Img_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 170, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo_Paginas.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Agregar_UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Agregar_UActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Btn_Agregar_UActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        agrInt.dispose();
    }//GEN-LAST:event_formMouseClicked

    private void BTN_VerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_VerMousePressed
        // TODO add your handling code here:
                this.Txt_Clave.setEchoChar((char)0);
    }//GEN-LAST:event_BTN_VerMousePressed

    private void BTN_VerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_VerMouseReleased
        // TODO add your handling code here:
                this.Txt_Clave.setEchoChar('\u2022');
    }//GEN-LAST:event_BTN_VerMouseReleased

    public Interfaz_agregar_Usuario agrInt=new Interfaz_agregar_Usuario();
    public DefaultTableModel tabla = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hacer todas las celdas no editables
            }
        };
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTN_Ver;
    public javax.swing.JButton Btn_Agregar_U;
    public javax.swing.JLabel Btn_Buscar;
    public javax.swing.JButton Btn_Eliminar_U;
    public javax.swing.JButton Btn_Modificar_U;
    public javax.swing.JCheckBox Ch_Clientes;
    public javax.swing.JCheckBox Ch_Compra;
    public javax.swing.JCheckBox Ch_Kardex;
    public javax.swing.JCheckBox Ch_Productos;
    public javax.swing.JCheckBox Ch_Proveedores;
    public javax.swing.JCheckBox Ch_Provincias;
    public javax.swing.JCheckBox Ch_Usuarios;
    public javax.swing.JCheckBox Ch_Venta;
    public javax.swing.JLabel Lbl_Img_Usuario;
    public javax.swing.JTable Tabla_Usuarios;
    public javax.swing.JTextField Texto_Buscar_U;
    public javax.swing.JPasswordField Txt_Clave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
