/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author Usuario
 */
public class Interfaz_agregar_Usuario extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form Interfaz_agregar_Usuario
     */
    public Interfaz_agregar_Usuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Barra_Mover = new javax.swing.JPanel();
        Txt_Usuario = new javax.swing.JTextField();
        Txt_Clave = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Provincias = new javax.swing.JCheckBox();
        Usuario = new javax.swing.JCheckBox();
        Kardex = new javax.swing.JCheckBox();
        Compra = new javax.swing.JCheckBox();
        Venta = new javax.swing.JCheckBox();
        Proveedores = new javax.swing.JCheckBox();
        Clientes = new javax.swing.JCheckBox();
        Productos = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        BTN_Cancelar = new javax.swing.JLabel();
        BTN_Agregar1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Barra_Mover.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Barra_Mover.setOpaque(false);
        Barra_Mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Barra_MoverMouseDragged(evt);
            }
        });
        Barra_Mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Barra_MoverMousePressed(evt);
            }
        });
        getContentPane().add(Barra_Mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 40));
        getContentPane().add(Txt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 150, 40));
        getContentPane().add(Txt_Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 150, 40));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 110, 30));

        jButton1.setText("Ver");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 60, -1));

        Provincias.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        Provincias.setText("Provincias");
        Provincias.setFocusable(false);
        getContentPane().add(Provincias, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 110, 40));

        Usuario.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        Usuario.setText("Usuarios");
        Usuario.setFocusable(false);
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 110, 40));

        Kardex.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        Kardex.setText("Kardex");
        Kardex.setFocusable(false);
        getContentPane().add(Kardex, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 110, 40));

        Compra.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        Compra.setText("Compra");
        Compra.setFocusable(false);
        getContentPane().add(Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 110, 40));

        Venta.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        Venta.setText("Venta");
        Venta.setToolTipText("");
        Venta.setFocusable(false);
        getContentPane().add(Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 110, 40));

        Proveedores.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        Proveedores.setText("Proveedores");
        Proveedores.setFocusable(false);
        getContentPane().add(Proveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 110, 40));

        Clientes.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        Clientes.setText("Clientes");
        Clientes.setFocusable(false);
        getContentPane().add(Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 110, 40));

        Productos.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        Productos.setText("Productos");
        Productos.setFocusable(false);
        getContentPane().add(Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 110, 40));

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 110, 30));

        BTN_Cancelar.setBackground(new java.awt.Color(159, 20, 24));
        BTN_Cancelar.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        BTN_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BTN_Cancelar.setText("CANCELAR");
        BTN_Cancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 0, 0), null, new java.awt.Color(255, 0, 0)));
        BTN_Cancelar.setOpaque(true);
        BTN_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_CancelarMouseClicked(evt);
            }
        });
        getContentPane().add(BTN_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 90, 30));

        BTN_Agregar1.setBackground(new java.awt.Color(159, 20, 24));
        BTN_Agregar1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        BTN_Agregar1.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Agregar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BTN_Agregar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 0, 0), null, new java.awt.Color(255, 0, 0)));
        BTN_Agregar1.setOpaque(true);
        getContentPane().add(BTN_Agregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Agregar_Fondo340-440.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_CancelarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BTN_CancelarMouseClicked

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        this.Txt_Clave.setEchoChar((char) 0);
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
        this.Txt_Clave.setEchoChar('\u2022');
    }//GEN-LAST:event_jButton1MouseReleased

    private void Barra_MoverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra_MoverMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_Barra_MoverMouseDragged

    private void Barra_MoverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra_MoverMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_Barra_MoverMousePressed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowLostFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_agregar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_agregar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_agregar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_agregar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_agregar_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel BTN_Agregar1;
    public javax.swing.JLabel BTN_Cancelar;
    private javax.swing.JPanel Barra_Mover;
    public javax.swing.JCheckBox Clientes;
    public javax.swing.JCheckBox Compra;
    public javax.swing.JCheckBox Kardex;
    public javax.swing.JCheckBox Productos;
    public javax.swing.JCheckBox Proveedores;
    public javax.swing.JCheckBox Provincias;
    public javax.swing.JPasswordField Txt_Clave;
    public javax.swing.JTextField Txt_Usuario;
    public javax.swing.JCheckBox Usuario;
    public javax.swing.JCheckBox Venta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
