/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author User
 */
public class Interfaz_agregarProd extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form agrProd
     */
    public Interfaz_agregarProd() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Barra_Mover = new javax.swing.JPanel();
        TXT_NombreProd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TXT_CodigoProd = new javax.swing.JTextField();
        Proveedor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BTN_Cancelar = new javax.swing.JLabel();
        BTN_Agregar1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fondo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Barra_Mover.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Barra_Mover.setOpaque(false);
        Barra_Mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Barra_MoverMouseDragged(evt);
            }
        });
        Barra_Mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Barra_MoverMousePressed(evt);
            }
        });
        getContentPane().add(Barra_Mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));
        getContentPane().add(TXT_NombreProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 145, 33));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel2.setText("Nombre del Producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 145, 31));

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel3.setText("Codigo del Producto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 145, 31));
        getContentPane().add(TXT_CodigoProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 145, 33));

        getContentPane().add(Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 145, 33));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel4.setText("Proveedor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 125, 31));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(37, 39, 44), null, null));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 190, 360));

        BTN_Cancelar.setBackground(new java.awt.Color(159, 20, 24));
        BTN_Cancelar.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        BTN_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BTN_Cancelar.setText("CANCELAR");
        BTN_Cancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 0, 0), null, new java.awt.Color(255, 0, 0)));
        BTN_Cancelar.setOpaque(true);
        BTN_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_CancelarMouseClicked(evt);
            }
        });
        getContentPane().add(BTN_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 90, 30));

        BTN_Agregar1.setBackground(new java.awt.Color(159, 20, 24));
        BTN_Agregar1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        BTN_Agregar1.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Agregar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BTN_Agregar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 0, 0), null, new java.awt.Color(255, 0, 0)));
        BTN_Agregar1.setOpaque(true);
        getContentPane().add(BTN_Agregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 90, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/AgregarPro_Fondo.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 450));

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_CancelarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BTN_CancelarMouseClicked

    private void Barra_MoverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra_MoverMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_Barra_MoverMouseDragged

    private void Barra_MoverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra_MoverMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_Barra_MoverMousePressed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
                this.dispose();
    }//GEN-LAST:event_formWindowLostFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_agregarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_agregarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_agregarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_agregarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_agregarProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel BTN_Agregar1;
    public javax.swing.JLabel BTN_Cancelar;
    private javax.swing.JPanel Barra_Mover;
    public javax.swing.JComboBox<String> Proveedor;
    public javax.swing.JTextField TXT_CodigoProd;
    public javax.swing.JTextField TXT_NombreProd;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
