/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.util.Date;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Interfaz_AgregarFactura extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form Interfaz_AgregarFacturas
     */
    public Interfaz_AgregarFactura() {
        initComponents();
        this.setLocationRelativeTo(null);
        Date fecha = new Date();
        this.Sel_Fecha.setDate(fecha);
        String columnas[] = {"Nombre", "Codigo", "Cantidad", "Precio Unitario", "Total"};
        this.tabla.setColumnIdentifiers(columnas);
        this.Tabla_Producto.setModel(tabla);
        this.Spi_Cantidad.setModel(new SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel = new javax.swing.JPanel();
        Combo_codCliente = new javax.swing.JComboBox<>();
        Lbl_codCliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Txt_CodFactura = new javax.swing.JTextField();
        Sel_Fecha = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        Combo_CodProducto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Txt_Precio = new javax.swing.JTextField();
        Spi_Cantidad = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Texto_Buscar_Prod = new javax.swing.JTextField();
        ComboBox_QueBusca = new javax.swing.JComboBox<>();
        Btn_Buscar_Prod = new javax.swing.JLabel();
        BTN_Cancelar = new javax.swing.JLabel();
        BTN_Agregar1 = new javax.swing.JLabel();
        Txt_DirCliente = new javax.swing.JTextField();
        Txt_NomCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Btn_ElimProd = new javax.swing.JLabel();
        TXT_Total = new javax.swing.JTextField();
        Btn_AgrProd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Producto = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpanel.setOpaque(false);
        jpanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpanelMouseDragged(evt);
            }
        });
        jpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpanelLayout = new javax.swing.GroupLayout(jpanel);
        jpanel.setLayout(jpanelLayout);
        jpanelLayout.setHorizontalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        jpanelLayout.setVerticalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 30));

        getContentPane().add(Combo_codCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 130, 30));

        Lbl_codCliente.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        Lbl_codCliente.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_codCliente.setText("Cedula:");
        getContentPane().add(Lbl_codCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 68, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo de factura:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        Txt_CodFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_CodFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_CodFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 110, 30));

        Sel_Fecha.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(Sel_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 110, 30));

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 70, -1));

        getContentPane().add(Combo_CodProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 210, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Producto:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));
        getContentPane().add(Txt_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 100, 30));
        getContentPane().add(Spi_Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 60, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio unitario:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cantidad:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, -1, -1));

        Texto_Buscar_Prod.setText("Buscar");
        getContentPane().add(Texto_Buscar_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 110, 30));

        ComboBox_QueBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Codigo" }));
        getContentPane().add(ComboBox_QueBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 80, 30));

        Btn_Buscar_Prod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BTN_Buscar.png"))); // NOI18N
        getContentPane().add(Btn_Buscar_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 35, 35));

        BTN_Cancelar.setBackground(new java.awt.Color(37, 39, 44));
        BTN_Cancelar.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        BTN_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BTN_Cancelar.setText("CANCELAR");
        BTN_Cancelar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BTN_Cancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, new java.awt.Color(102, 102, 102)));
        BTN_Cancelar.setOpaque(true);
        BTN_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_CancelarMouseClicked(evt);
            }
        });
        getContentPane().add(BTN_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 90, 30));

        BTN_Agregar1.setBackground(new java.awt.Color(37, 39, 44));
        BTN_Agregar1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        BTN_Agregar1.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Agregar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BTN_Agregar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BTN_Agregar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, new java.awt.Color(102, 102, 102)));
        BTN_Agregar1.setOpaque(true);
        BTN_Agregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_Agregar1MouseClicked(evt);
            }
        });
        getContentPane().add(BTN_Agregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 90, 30));

        Txt_DirCliente.setEditable(false);
        Txt_DirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_DirClienteActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_DirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 170, 30));

        Txt_NomCliente.setEditable(false);
        Txt_NomCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NomClienteActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_NomCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 170, 30));

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Direccion:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        Btn_ElimProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Compra_qui.png"))); // NOI18N
        getContentPane().add(Btn_ElimProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 50, 40));

        TXT_Total.setEditable(false);
        TXT_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_TotalActionPerformed(evt);
            }
        });
        getContentPane().add(TXT_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, 70, 30));

        Btn_AgrProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Compra_agr.png"))); // NOI18N
        getContentPane().add(Btn_AgrProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 50, 40));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        Tabla_Producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabla_Producto.setGridColor(new java.awt.Color(102, 102, 102));
        Tabla_Producto.setRowHeight(30);
        Tabla_Producto.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Tabla_Producto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 810, 240));

        jLabel9.setText("Total:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 50, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Agregar_Fondo870-520.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_CodFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_CodFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_CodFacturaActionPerformed

    private void Txt_DirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_DirClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_DirClienteActionPerformed

    private void Txt_NomClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NomClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NomClienteActionPerformed

    private void TXT_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_TotalActionPerformed

    private void BTN_CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_CancelarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BTN_CancelarMouseClicked

    private void jpanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jpanelMouseDragged

    private void jpanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jpanelMousePressed

    private void BTN_Agregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_Agregar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_Agregar1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_AgregarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_AgregarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_AgregarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_AgregarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_AgregarFactura().setVisible(true);
            }
        });
    }
    public DefaultTableModel tabla = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Hacer todas las celdas no editables
        }
    };
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel BTN_Agregar1;
    public javax.swing.JLabel BTN_Cancelar;
    public javax.swing.JLabel Btn_AgrProd;
    public javax.swing.JLabel Btn_Buscar_Prod;
    public javax.swing.JLabel Btn_ElimProd;
    public javax.swing.JComboBox<String> ComboBox_QueBusca;
    public javax.swing.JComboBox<String> Combo_CodProducto;
    public javax.swing.JComboBox<String> Combo_codCliente;
    public javax.swing.JLabel Lbl_codCliente;
    public com.toedter.calendar.JDateChooser Sel_Fecha;
    public javax.swing.JSpinner Spi_Cantidad;
    public javax.swing.JTextField TXT_Total;
    public javax.swing.JTable Tabla_Producto;
    public javax.swing.JTextField Texto_Buscar_Prod;
    public javax.swing.JTextField Txt_CodFactura;
    public javax.swing.JTextField Txt_DirCliente;
    public javax.swing.JTextField Txt_NomCliente;
    public javax.swing.JTextField Txt_Precio;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanel;
    // End of variables declaration//GEN-END:variables
}
